name: 'Kisonar JEE CI'

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: GitHub checkout action
        uses: actions/checkout@v3
      - name: Setup Java 18
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '24'
      - name: Run Maven compilation, unit testing & packaging
        run: mvn clean install

  analyze-plugins:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: GitHub checkout action
        uses: actions/checkout@v3
      - name: Setup Java 18
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '24'
      - name: Run Maven plugin updates
        run: mvn versions:display-plugin-updates

  analyze-dependencies:
    needs: analyze-plugins
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: GitHub checkout action
        uses: actions/checkout@v3
      - name: Setup Java 18
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '24'
      - name: Run Maven dependencies updates
        run: mvn versions:display-dependency-updates

  analyze-dependencies-duplicates:
    needs: analyze-dependencies
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: GitHub checkout action
        uses: actions/checkout@v3
      - name: Setup Java 18
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '24'
      - name: Run Maven dependencies duplicates check
        run: mvn dependency:analyze-duplicate